CREATE TABLE IF NOT EXISTS public.people (
	id UUID PRIMARY KEY NOT NULL,
	nickname VARCHAR(32) UNIQUE NOT NULL,
	name VARCHAR(100) NOT NULL,
	birthdate DATE NOT NULL,
	stack VARCHAR(1024),
	search VARCHAR(1156)
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_stack_fulltext ON public.people USING GIST (search GIST_TRGM_OPS);