version: "3.5"
services:
  db:
    image: postgres:latest
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    network_mode: host
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'
  
  cache:
    hostname: cache
    image: redis:latest
    command: redis-server --save "" --appendonly no
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'
  
  api01:
    image: banckend-web
    hostname: api01
    depends_on:
      - db
      - cache
    environment:
      - ConnectionStrings__Npgsql=Host=localhost;Username=admin;Password=123;Database=rinha;
      - ConnectionStrings__Redis=localhost:6379,abortConnect=false
      # - ASPNETCORE_ENVIRONMENT=Development
      - Concurrency__BufferSize=15
      - Concurrency__BufferExpirationMilliseconds=5000
      - Concurrency__CacheReplicationCompensationMilliseconds=500
      - ASPNETCORE_URLS=http://+:8081
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
  
  api02:
    image: banckend-web
    hostname: api02
    depends_on:
      - db
      - cache
    environment:
      - ConnectionStrings__Npgsql=Host=localhost;Username=admin;Password=123;Database=rinha;
      - ConnectionStrings__Redis=localhost:6379,abortConnect=false
      # - ASPNETCORE_ENVIRONMENT=Development
      - Concurrency__BufferSize=15
      - Concurrency__BufferExpirationMilliseconds=5000
      - Concurrency__CacheReplicationCompensationMilliseconds=500
      - ASPNETCORE_URLS=http://+:8082
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'